import { Category, Worker, Review, Booking, CallRecord, ChatMessage } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Electrician',
    icon_name: 'Zap',
    description: 'Bijli ki wiring, UPS, breaker repair aur generator maintenance',
  },
  {
    id: 'cat-2',
    name: 'Plumber',
    icon_name: 'Wrench',
    description: 'Paani ke pipe, motor repair, sanitary ware aur leakage solutions',
  },
  {
    id: 'cat-3',
    name: 'AC Technician',
    icon_name: 'Wind',
    description: 'AC servicing, gas refilling, installation aur compressor repair',
  },
  {
    id: 'cat-4',
    name: 'Carpenter',
    icon_name: 'Hammer',
    description: 'Darwaze, furniture repair, kitchen cabinets aur custom woodwork',
  },
  {
    id: 'cat-5',
    name: 'Tailor',
    icon_name: 'Scissors',
    description: 'Ghar bethay ladies & gents kapray silai, alteration aur design',
  },
  {
    id: 'cat-6',
    name: 'Tutor',
    icon_name: 'BookOpen',
    description: 'Matric, FSC, O/A Levels, Mathematics, Science aur English home tuition',
  },
  {
    id: 'cat-7',
    name: 'Driver',
    icon_name: 'Car',
    description: 'Personal, family, outstation aur automatic/manual car drivers',
  },
  {
    id: 'cat-8',
    name: 'Makeup Artist',
    icon_name: 'Sparkles',
    description: 'Bridal, party makeup, hairstyling aur skin grooming at home',
  },
  {
    id: 'cat-9',
    name: 'Painter',
    icon_name: 'Paintbrush',
    description: 'Ghar ki whitening, wall painting, texture finish aur waterproofing',
  },
  {
    id: 'cat-10',
    name: 'Mehndi Artist',
    icon_name: 'Feather',
    description: 'Bridal mehndi, eid & function designs, arabic & pakistani styles',
  },
  {
    id: 'cat-11',
    name: 'Home Cook',
    icon_name: 'Utensils',
    description: 'Rozmara ke khana, daawat, biryani, karahi aur hygienic home catering',
  },
];

export const INITIAL_WORKERS: Worker[] = [
  {
    id: 'w-1',
    user_id: 'u-w1',
    name: 'Mohammad Tariq',
    phone: '03001234567',
    email: 'tariq.electric@gmail.com',
    cnic_number: '42101-1234567-1',
    cnic_photo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    profile_photo_url: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=400&auto=format&fit=crop&q=80',
    category: 'Electrician',
    bio: 'Experienced electrician with 8 years in home & commercial wiring. Specializing in DB box setup, UPS installations, and short-circuit troubleshooting across Gulshan & Johar.',
    trust_summary: 'Customers frequently highlight Tariq’s extreme punctuality, transparent pricing without hidden charges, and clean wiring work.',
    years_experience: 8,
    rate_type: 'hourly',
    rate_amount: 800,
    city: 'Karachi',
    area: 'Gulshan-e-Iqbal',
    is_verified: true,
    is_available: true,
    average_rating: 4.9,
    total_reviews: 28,
    created_at: '2025-01-10T10:00:00Z',
  },
  {
    id: 'w-2',
    user_id: 'u-w2',
    name: 'Zubair Ahmed',
    phone: '03129876543',
    email: 'zubair.ac@gmail.com',
    cnic_number: '35202-8765432-3',
    cnic_photo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    profile_photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    category: 'AC Technician',
    bio: 'Certified inverter AC specialist with 10 years experience in master servicing, R32/R410 gas refill, and PCB board repairs in Gulberg and Model Town.',
    trust_summary: 'Highly recommended for quick AC cooling fixes and honest advice on whether gas refilling is actually required.',
    years_experience: 10,
    rate_type: 'per-job',
    rate_amount: 2500,
    city: 'Lahore',
    area: 'Gulberg III',
    is_verified: true,
    is_available: true,
    average_rating: 4.8,
    total_reviews: 34,
    created_at: '2025-01-15T12:00:00Z',
  },
  {
    id: 'w-3',
    user_id: 'u-w3',
    name: 'Shagufta Begum',
    phone: '03335554433',
    email: 'shagufta.stitching@gmail.com',
    cnic_number: '61101-5554433-2',
    cnic_photo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    profile_photo_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
    category: 'Tailor',
    bio: 'Master boutique tailor offering home pick & drop stitching for designer lawn, party wear, and formal suits. Over 12 years of perfection in finishing.',
    trust_summary: 'Clients love her exact fitting accuracy, beautiful piping details, and guaranteed on-time delivery before event dates.',
    years_experience: 12,
    rate_type: 'per-job',
    rate_amount: 1800,
    city: 'Islamabad',
    area: 'F-8/2',
    is_verified: true,
    is_available: true,
    average_rating: 5.0,
    total_reviews: 42,
    created_at: '2025-01-18T09:00:00Z',
  },
  {
    id: 'w-4',
    user_id: 'u-w4',
    name: 'Sir Hamza Malik',
    phone: '03014443322',
    email: 'hamza.tuition@gmail.com',
    cnic_number: '42201-4443322-9',
    cnic_photo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    profile_photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    category: 'Tutor',
    bio: 'M.Sc Physics graduate offering conceptual home tuition for O/A Levels, Matric, and FSC Mathematics & Physics in DHA & Clifton.',
    trust_summary: 'Parents praise Sir Hamza for improving student grades significantly within weeks and building exam confidence.',
    years_experience: 6,
    rate_type: 'hourly',
    rate_amount: 1500,
    city: 'Karachi',
    area: 'DHA Phase 6',
    is_verified: true,
    is_available: true,
    average_rating: 4.9,
    total_reviews: 19,
    created_at: '2025-02-01T14:00:00Z',
  },
  {
    id: 'w-5',
    user_id: 'u-w5',
    name: 'Rashid Khan',
    phone: '03451122334',
    email: 'rashid.plumber@gmail.com',
    cnic_number: '37405-1122334-7',
    cnic_photo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    profile_photo_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80',
    category: 'Plumber',
    bio: 'Expert sanitary & pipeline plumber skilled in underground leakage detection, water motor fitting, and bathroom fitting installations.',
    trust_summary: 'Known for fixing complex leakages quickly without damaging surrounding tiles unnecessarily.',
    years_experience: 7,
    rate_type: 'hourly',
    rate_amount: 700,
    city: 'Rawalpindi',
    area: 'Commercial Market',
    is_verified: true,
    is_available: true,
    average_rating: 4.7,
    total_reviews: 15,
    created_at: '2025-02-05T11:00:00Z',
  },
  {
    id: 'w-6',
    user_id: 'u-w6',
    name: 'Kiran Shah',
    phone: '03217778899',
    email: 'kiran.makeup@gmail.com',
    cnic_number: '35201-7778899-4',
    cnic_photo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    profile_photo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    category: 'Makeup Artist',
    bio: 'Professional freelance makeup artist trained in soft glam, bridal, and barat looks using authentic high-end products at your doorstep.',
    trust_summary: 'Clients consistently rave about her flawless skin blend, long-lasting hair setting, and friendly gentle demeanor.',
    years_experience: 5,
    rate_type: 'per-job',
    rate_amount: 5000,
    city: 'Lahore',
    area: 'DHA Phase 5',
    is_verified: true,
    is_available: true,
    average_rating: 4.9,
    total_reviews: 51,
    created_at: '2025-02-10T16:00:00Z',
  },
  {
    id: 'w-7',
    user_id: 'u-w7',
    name: 'Asif Mehmood',
    phone: '03348889900',
    email: 'asif.driver@gmail.com',
    cnic_number: '61101-8889900-1',
    cnic_photo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    profile_photo_url: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&auto=format&fit=crop&q=80',
    category: 'Driver',
    bio: 'Punctual and courteous driver with valid HTV/LTV license. Experienced in both automatic and manual luxury vehicles for city commute and intercity trips.',
    trust_summary: 'Customers commend Asif for safe defensive driving, respectful etiquette, and thorough route knowledge of motorways.',
    years_experience: 9,
    rate_type: 'hourly',
    rate_amount: 1000,
    city: 'Islamabad',
    area: 'G-11',
    is_verified: true,
    is_available: true,
    average_rating: 4.8,
    total_reviews: 22,
    created_at: '2025-02-12T08:00:00Z',
  },
  {
    id: 'w-8',
    user_id: 'u-w8',
    name: 'Kamran Ustad',
    phone: '03026665544',
    email: 'kamran.carpenter@gmail.com',
    cnic_number: '33100-6665544-5',
    cnic_photo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    profile_photo_url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&auto=format&fit=crop&q=80',
    category: 'Carpenter',
    bio: 'Craftsman specialized in wooden door fitting, bed repair, wardrobe sliding tracks, and custom kitchen cabinet modifications.',
    trust_summary: 'Appreciated for sturdy repair work, clean wood sanding, and reasonable estimates.',
    years_experience: 14,
    rate_type: 'hourly',
    rate_amount: 900,
    city: 'Faisalabad',
    area: "People's Colony",
    is_verified: true,
    is_available: true,
    average_rating: 4.6,
    total_reviews: 18,
    created_at: '2025-02-14T13:00:00Z',
  },
  {
    id: 'w-9',
    user_id: 'u-w9',
    name: 'Shahid Raza',
    phone: '03153332211',
    email: 'shahid.painter@gmail.com',
    cnic_number: '42301-3332211-8',
    cnic_photo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    profile_photo_url: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=400&auto=format&fit=crop&q=80',
    category: 'Painter',
    bio: 'Professional wall painter specializing in Asian Paints, Matt enamel, texture designs, and dampness/seep treatment for homes.',
    trust_summary: 'Homeowners love his neat masking, thorough floor protection while painting, and vibrant smooth finishes.',
    years_experience: 11,
    rate_type: 'hourly',
    rate_amount: 850,
    city: 'Karachi',
    area: 'PECHS',
    is_verified: true,
    is_available: true,
    average_rating: 4.8,
    total_reviews: 26,
    created_at: '2025-02-15T15:00:00Z',
  },
  {
    id: 'w-10',
    user_id: 'u-w10',
    name: 'Chef Naseem',
    phone: '03229990011',
    email: 'naseem.cook@gmail.com',
    cnic_number: '35202-9990011-6',
    cnic_photo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    profile_photo_url: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400&auto=format&fit=crop&q=80',
    category: 'Home Cook',
    bio: 'Hygienic home cook for family dinners, small dawat events, authentic chicken biryani, mutton karahi, and traditional Pakistani desserts.',
    trust_summary: 'Guests always applaud Chef Naseem for restaurant-grade taste, spotless kitchen cleanliness, and great portion planning.',
    years_experience: 15,
    rate_type: 'per-job',
    rate_amount: 3000,
    city: 'Lahore',
    area: 'Model Town',
    is_verified: true,
    is_available: true,
    average_rating: 4.9,
    total_reviews: 39,
    created_at: '2025-02-20T10:00:00Z',
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    booking_id: 'b-101',
    customer_id: 'u-c1',
    customer_name: 'Tariq M.',
    worker_id: 'w-1',
    rating: 5,
    comment: 'Zabrduat kaam kiya! Time per pohnche aur UPS ki wiring minute mein set kar di. Rate bhi bohot munasib tha.',
    created_at: '2025-02-21T11:00:00Z',
  },
  {
    id: 'rev-2',
    booking_id: 'b-102',
    customer_id: 'u-c2',
    customer_name: 'Amina K.',
    worker_id: 'w-1',
    rating: 5,
    comment: 'Very professional electrician. Cleaned up after work. Will hire again!',
    created_at: '2025-02-22T14:30:00Z',
  },
  {
    id: 'rev-3',
    booking_id: 'b-103',
    customer_id: 'u-c3',
    customer_name: 'Bilal R.',
    worker_id: 'w-2',
    rating: 5,
    comment: 'AC ki cooling ab ekdum chill ho gayi hai. Master servicing bohot acchi ki.',
    created_at: '2025-02-23T16:00:00Z',
  },
  {
    id: 'rev-4',
    booking_id: 'b-104',
    customer_id: 'u-c4',
    customer_name: 'Farha S.',
    worker_id: 'w-3',
    rating: 5,
    comment: 'Shagufta Baji ne eid suit ki fitting perfect ki. Time per kapray mil gaye!',
    created_at: '2025-02-24T10:15:00Z',
  },
  {
    id: 'rev-5',
    booking_id: 'b-105',
    customer_id: 'u-c5',
    customer_name: 'Dr. Saad H.',
    worker_id: 'w-4',
    rating: 5,
    comment: 'Sir Hamza is excellent for O Level Physics. My son scored an A grade in mock exam.',
    created_at: '2025-02-25T18:00:00Z',
  },
  {
    id: 'rev-6',
    booking_id: 'b-106',
    customer_id: 'u-c6',
    customer_name: 'Sadia N.',
    worker_id: 'w-6',
    rating: 5,
    comment: 'Party makeup bohot natural tha aur night tak fresh raha. Thank you Kiran!',
    created_at: '2025-02-26T20:00:00Z',
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'b-101',
    customer_id: 'u-c1',
    customer_name: 'Tariq M.',
    customer_phone: '03001112233',
    worker_id: 'w-1',
    worker_name: 'Mohammad Tariq',
    worker_photo: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=400&auto=format&fit=crop&q=80',
    worker_phone: '03001234567',
    category: 'Electrician',
    date_needed: '2025-02-20',
    time_preference: 'Morning (9am - 12pm)',
    address: 'House 42, Block 4, Gulshan-e-Iqbal, Karachi',
    description: 'UPS automatic changeover switch not working and main DB box tripping.',
    status: 'completed',
    booking_amount: 1600,
    commission_amount: 240,
    commission_status: 'paid',
    created_at: '2025-02-19T10:00:00Z',
    completed_at: '2025-02-20T12:00:00Z',
    has_review: true,
  },
  {
    id: 'b-102',
    customer_id: 'u-c2',
    customer_name: 'Amina K.',
    customer_phone: '03214445566',
    worker_id: 'w-2',
    worker_name: 'Zubair Ahmed',
    worker_photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    worker_phone: '03129876543',
    category: 'AC Technician',
    date_needed: '2025-03-01',
    time_preference: 'Afternoon (12pm - 4pm)',
    address: '154-H, Gulberg III, Lahore',
    description: 'Split AC master servicing and check gas pressure before summer.',
    status: 'accepted',
    booking_amount: 2500,
    commission_amount: 375,
    commission_status: 'pending',
    created_at: '2025-02-26T11:00:00Z',
  },
  {
    id: 'b-103',
    customer_id: 'u-c3',
    customer_name: 'Usman Ali',
    customer_phone: '03337778899',
    worker_id: 'w-1',
    worker_name: 'Mohammad Tariq',
    worker_photo: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=400&auto=format&fit=crop&q=80',
    worker_phone: '03001234567',
    category: 'Electrician',
    date_needed: '2025-03-02',
    time_preference: 'Evening (4pm - 8pm)',
    address: 'Flat 302, Johar Complex, Block 13, Karachi',
    description: 'Ceiling fans speed dimmers replacement and short circuit in lounge.',
    status: 'pending',
    booking_amount: 1200,
    commission_amount: 180,
    commission_status: 'pending',
    created_at: '2025-02-28T14:20:00Z',
  },
];

export const INITIAL_CALLS: CallRecord[] = [
  {
    id: 'call-101',
    booking_id: 'b-101',
    caller_id: 'u-c1',
    caller_name: 'Tariq M.',
    caller_photo: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200',
    caller_role: 'customer',
    callee_id: 'w-1',
    callee_name: 'Mohammad Tariq',
    callee_photo: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=400',
    callee_role: 'worker',
    category: 'Electrician',
    status: 'ended',
    duration_seconds: 142,
    created_at: '2025-02-19T10:05:00Z',
  },
  {
    id: 'call-102',
    booking_id: 'b-102',
    caller_id: 'w-2',
    caller_name: 'Zubair Ahmed',
    caller_photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    caller_role: 'worker',
    callee_id: 'u-c2',
    callee_name: 'Amina K.',
    callee_photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200',
    callee_role: 'customer',
    category: 'AC Technician',
    status: 'ended',
    duration_seconds: 98,
    created_at: '2025-02-26T11:15:00Z',
  },
  {
    id: 'call-103',
    booking_id: 'b-103',
    caller_id: 'u-c3',
    caller_name: 'Usman Ali',
    caller_photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200',
    caller_role: 'customer',
    callee_id: 'w-1',
    callee_name: 'Mohammad Tariq',
    callee_photo: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=400',
    callee_role: 'worker',
    category: 'Electrician',
    status: 'missed',
    duration_seconds: 0,
    created_at: '2025-02-28T14:22:00Z',
  },
];

export const INITIAL_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: 'msg-1',
    booking_id: 'b-101',
    sender_id: 'u-c1',
    sender_name: 'Tariq M.',
    sender_role: 'customer',
    text: 'Assalam-o-Alaikum Tariq Bhai, main ne UPS wiring ke liye booking ki hai.',
    created_at: '2025-02-19T10:01:00Z',
  },
  {
    id: 'msg-2',
    booking_id: 'b-101',
    sender_id: 'w-1',
    sender_name: 'Mohammad Tariq',
    sender_role: 'worker',
    text: 'Walaikum Assalam! Ji main ne request dekh li hai. Main kal morning 10 baje aunga.',
    created_at: '2025-02-19T10:03:00Z',
  },
];

